server:
    port: 8887
    servlet:
        session:
            timeout: 15552000
github:
    client:
      id: 2859958f9f059979ed3a
      secret: 10a5ce491fd6b7cd137efdc1ac763261f7d3b6fc
    redirect:
      uri: http://localhost:8887/callback
#      这是测试
#      这是测试2
#      这也是测试2
#      这是master测试5
#      这是测试三
#      这是测试4
#      这是测试5
#      这是dev未提交测试6
#      这是master测试6
#      这是dev测试7
ucloud:
    ufile:
       public-key: TOKEN_f465454a-f3ab-4c9b-91a5-c7babf59cc38
       private-key: 18977163-f21e-4deb-a2e3-9bfa0b888ba5
       bucket-name: mawen
       region: cn-bj
       suffix: ufileos.com
       expires: 315360000
spring:
    datasource:
        url: jdbc:h2:~/community
        username: sa
        password: 123
        driver-class-name: org.h2.Driver
    servlet:
        multipart.max-file-size: 20MB
        multipart.max-request-size: 20MB
mybatis:
    configuration:
        map-underscore-to-camel-case: true
    type-aliases-package: life.majiang.community.mapper
    mapper-locations: classpath:mapper/*.xml
  #原配置
  #logging.file=logs/community.log
  #logging.level.root=info
  #logging.file.max-history=15
  #logging.file.max-size=100MB
logging:
    config: classpath:logback-spring.xml
